version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version      
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 353719963446.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=353719963446.dkr.ecr.us-west-2.amazonaws.com/devops-build-ecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...      
      - docker build -t devops-build-ecr:latest .
      - docker tag devops-build-ecr:latest 353719963446.dkr.ecr.us-west-2.amazonaws.com/devops-build-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...      
      - docker push 353719963446.dkr.ecr.us-west-2.amazonaws.com/devops-build-ecr:latest
      - echo Writing image definitions file...
      - printf '[{"name":"devops","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: 
      - imagedefinitions.json
